# Generated by Django 3.0 on 2020-01-07 19:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('knowledge', '0002_auto_20191217_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
