# Generated by Django 3.0 on 2019-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knovledg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knovledg',
            name='short_desc',
            field=models.TextField(default='sdf'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
